export const PRODUCT_IDS = {
  KEYBOARD: "p1",
  MOUSE: "p2",
  MONITOR_ARM: "p3",
  LAPTOP_POUCH: "p4",
  SPEAKER: "p5",
};

export const DISCOUNT_RATES = {
  DEFAULT: 0.1,
  KEYBOARD: 0.1,
  MOUSE: 0.15,
  MONITOR_ARM: 0.2,
  LAPTOP_POUCH: 0.05,
  SPEAKER: 0.25,
  BULK_DISCOUNT: 0.25,
  TUESDAY_DISCOUNT: 0.1,
  LIGHTNING_SALE: 0.2,
  SUGGESTED_DISCOUNT: 0.05,
};

export const BULK_ITEM_COUNT = 10;